version: 2.1

jobs:
  build-image:
    machine: true
    steps:
      - checkout
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker build and push
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              IMAGE_TAG="$CIRCLE_TAG"
            elif [ "$CIRCLE_BRANCH" = "master" ]; then
              IMAGE_TAG="latest"
            else
              IMAGE_TAG="$CIRCLE_BRANCH"
            fi
            docker build -t trap/traq-ui:$IMAGE_TAG .
            docker push trap/traq-ui:$IMAGE_TAG
  build:
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: module install
          command: npm ci
      - run:
          name: build
          command: npm run build

workflows:
  version: 2
  main:
    jobs:
      - build
      - build-image:
          filters:
            branches:
              only: master
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}.*/
